import logging
from typing import Dict, Any, Optional
import json
from datetime import timedelta

logger = logging.getLogger(__name__)

def format_timestamp(seconds: float) -> str:
    """Convert seconds to SRT/VTT timestamp format."""
    td = timedelta(seconds=seconds)
    hours = td.seconds // 3600
    minutes = (td.seconds % 3600) // 60
    seconds = td.seconds % 60
    milliseconds = td.microseconds // 1000
    return f"{hours:02d}:{minutes:02d}:{seconds:02d},{milliseconds:03d}"

def to_srt(segments: list) -> str:
    """Convert segments to SRT format."""
    srt_content = ""
    for i, segment in enumerate(segments, 1):
        start = format_timestamp(segment['start'])
        end = format_timestamp(segment['end'])
        text = segment['text'].strip()
        srt_content += f"{i}\n{start} --> {end}\n{text}\n\n"
    return srt_content

def to_vtt(segments: list) -> str:
    """Convert segments to VTT format."""
    vtt_content = "WEBVTT\n\n"
    for i, segment in enumerate(segments, 1):
        start = format_timestamp(segment['start']).replace(',', '.')
        end = format_timestamp(segment['end']).replace(',', '.')
        text = segment['text'].strip()
        vtt_content += f"{start} --> {end}\n{text}\n\n"
    return vtt_content

def to_ass(segments: list, settings: Dict[str, Any]) -> str:
    """Convert segments to ASS format with custom styling."""
    ass_header = f"""[Script Info]
Title: Auto-generated by Whisper
ScriptType: v4.00+
Collisions: Normal
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,{settings['Fontname']},{settings['Fontsize']},{settings['PrimaryColour']},{settings['SecondaryColour']},{settings['OutlineColour']},{settings['BackColour']},{settings['Bold']},{settings['Italic']},{settings['Underline']},{settings['StrikeOut']},{settings['ScaleX']},{settings['ScaleY']},{settings['Spacing']},{settings['Angle']},{settings['BorderStyle']},{settings['Outline']},{settings['Shadow']},{settings['Alignment']},{settings['MarginL']},{settings['MarginR']},{settings['MarginV']},{settings['Encoding']}

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
    
    ass_content = ass_header
    for segment in segments:
        start = format_timestamp(segment['start']).replace(',', '.')
        end = format_timestamp(segment['end']).replace(',', '.')
        text = segment['text'].strip()
        ass_content += f"Dialogue: 0,{start},{end},Default,,0,0,0,,{text}\n"
    
    return ass_content

def format_transcription(result: Dict[str, Any], output_format: str, ass_settings: Optional[Dict[str, Any]] = None) -> str:
    """Format transcription results into the requested format."""
    try:
        segments = result.get('segments', [])
        
        if output_format == "json":
            return json.dumps(result, ensure_ascii=False, indent=2)
        elif output_format == "srt":
            return to_srt(segments)
        elif output_format == "vtt":
            return to_vtt(segments)
        elif output_format == "ass":
            if not ass_settings:
                from ..models.ass_settings import AssSettings
                ass_settings = AssSettings().dict()
            return to_ass(segments, ass_settings)
        else:
            raise ValueError(f"Unsupported output format: {output_format}")
            
    except Exception as e:
        logger.error(f"Error formatting transcription: {str(e)}")
        raise 